ProyectoDeAula3/Controllers/IdeasDeNegocioController.cs
using ProyectoDeAula3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoDeAula3.Controllers
{
    public class IdeasDeNegocioController : Controller
    {
        private static List<IdeaDeNegocio> ideasDeNegocio = new List<IdeaDeNegocio>();

        public List<Departamento> ObtenerListaDeDepartamentos()
        {
         

            var departamentos = new List<Departamento>
    {
        new Departamento { Codigo = 01, Nombre = "Departamento 1" },
        new Departamento { Codigo = 02, Nombre = "Departamento 2" },
        new Departamento { Codigo = 03, Nombre = "Departamento 3" },
        
    };

            return departamentos;
        }

        public List<string> ObtenerListaDeHerramientas4RI()
        {
           

            var herramientas4RI = new List<string>
    {
        "Inteligencia Artificial",
        "Internet de las Cosas (IoT)",
        "Big Data",
        "Blockchain",
        "Realidad Virtual",
        
    };

            return herramientas4RI;
        }


        public ActionResult Index()
        {
            return View(ideasDeNegocio);
        }

        public ActionResult Editar()
        {
            return View();
        }

        public ActionResult Crear()
        {

            List<string> herramientas4RI = ObtenerListaDeHerramientas4RI();

            
            ViewBag.Herramientas4RI = new SelectList(herramientas4RI);

            ViewBag.Departamentos = ObtenerListaDeDepartamentos();

            return View();
           
        }

        public List<IdeaDeNegocio> ObtenerTodasLasIdeasDeNegocio()
        {
           
            return ideasDeNegocio;
        }

        public IdeaDeNegocio ObtenerIdeaConMayorImpacto()
        {
            
            var todasLasIdeas = ObtenerTodasLasIdeasDeNegocio();

            
            var ideaMayorImpacto = todasLasIdeas.OrderByDescending(i => i.ImpactoSocialOEconomico).FirstOrDefault();

            return ideaMayorImpacto;
        }

        public IdeaDeNegocio ObtenerIdeaConMayorIngresos()
        {
            
            var todasLasIdeas = ObtenerTodasLasIdeasDeNegocio();

            
            var ideaMayorIngresos = todasLasIdeas.OrderByDescending(i => i.IngresosGenerados3Anios).FirstOrDefault();

            return ideaMayorIngresos;
        }

        public List<IdeaDeNegocio> ObtenerIdeasMasRentables()
        {
            
            var todasLasIdeas = ObtenerTodasLasIdeasDeNegocio();

           
            var ideasOrdenadasPorIngresos = todasLasIdeas.OrderByDescending(i => i.IngresosGenerados3Anios).ToList();

            
            var ideasMasRentables = ideasOrdenadasPorIngresos.Take(3).ToList();

            return ideasMasRentables;
        }

        public List<IdeaDeNegocio> ObtenerIdeasConImpactoEnMasDe3Departamentos()
        {
            
            var todasLasIdeas = ObtenerTodasLasIdeasDeNegocio();

            
            var ideasConImpactoEnMasDe3Departamentos = todasLasIdeas
                .Where(i => i.DepartamentosBeneficiados.Count > 3)
                .ToList();

            return ideasConImpactoEnMasDe3Departamentos;
        }

        public List<IdeaDeNegocio> ObtenerIdeasConHerramientas4RI()
        {
          
            var todasLasIdeas = ObtenerTodasLasIdeasDeNegocio();

            
            var ideasConHerramientas4RI = todasLasIdeas
                .Where(i => i.Herramientas4RI != null && i.Herramientas4RI.Any())
                .ToList();

            return ideasConHerramientas4RI;
        }

        public List<IdeaDeNegocio> ObtenerIdeasDesarrolloSostenible()
        {
          
            var todasLasIdeas = ObtenerTodasLasIdeasDeNegocio();
            var ideasDesarrolloSostenible = todasLasIdeas
                .Where(idea => idea.ImpactoSocialOEconomico != null &&
                               idea.ImpactoSocialOEconomico.IndexOf("Desarrollo sostenible", StringComparison.OrdinalIgnoreCase) >= 0)
                .ToList();

            return ideasDesarrolloSostenible;
        }

        private List<string> FrasesEspecificas = new List<string>
{
    "Territorios inteligentes",
    "Transicion energetica"
};

        public List<IdeaDeNegocio> ObtenerIdeasConFrasesEspecificas()
        {
         
            var todasLasIdeas = ObtenerTodasLasIdeasDeNegocio();

           
            var ideasConFrasesEspecificas = todasLasIdeas
                .Where(idea => idea.ImpactoSocialOEconomico != null &&
                               FrasesEspecificas.Any(frase =>
                                   idea.ImpactoSocialOEconomico.IndexOf(frase, StringComparison.OrdinalIgnoreCase) >= 0))
                .ToList();

            return ideasConFrasesEspecificas;
        }

        public IdeaDeNegocio ObtenerIdeaConMayorInversionEnInfraestructura()
        {
            
            var todasLasIdeas = ObtenerTodasLasIdeasDeNegocio();

          
            var ideaMayorInversion = todasLasIdeas
                .OrderByDescending(idea => idea.ValorInversionInfraestructura)
                .FirstOrDefault(); 

            return ideaMayorInversion;
        }


        [HttpPost]
        public ActionResult Crear(IdeaDeNegocio idea) { 
                

        
         
                
                idea.Codigo = ideasDeNegocio.Count + 1;

                
                ideasDeNegocio.Add(idea);

                
                return RedirectToAction("Index");
            
        }

        public ActionResult Detalles()
        {


            return View();
        }

        public ActionResult IdeaConMayorImpacto()
        {
            
            var ideaMayorImpacto = ObtenerIdeaConMayorImpacto();
            var ideaMayorIngresos = ObtenerIdeaConMayorIngresos();

            return View(new Tuple<IdeaDeNegocio, IdeaDeNegocio>(ideaMayorImpacto, ideaMayorIngresos));
        }

        public ActionResult IdeasMasRentables()
        {
            
            var ideasRentables = ObtenerIdeasMasRentables();

            return View(ideasRentables);
        }


        public ActionResult IdeasConImpactoEnMasDe3Departamentos()
        {
           
            var ideasConImpacto = ObtenerIdeasConImpactoEnMasDe3Departamentos();

            return View(ideasConImpacto);
        }

        public ActionResult IdeasConHerramientas4RI()
        {
            
            var ideasConHerramientas4RI = ObtenerIdeasConHerramientas4RI();

            return View(ideasConHerramientas4RI);
        }

        public ActionResult IdeasConFrasesEspecificas()
        {
            
            var ideasConFrasesEspecificas = ObtenerIdeasConFrasesEspecificas();

            return View(ideasConFrasesEspecificas);
        }

        public ActionResult IdeaConMayorInversionEnInfraestructura()
        {
            
            var ideaMayorInversion = ObtenerIdeaConMayorInversionEnInfraestructura();

            return View(ideaMayorInversion);
        }



        [HttpPost]
        public ActionResult AgregarIntegrante(int codigo, IntegranteEquipo integrante)
        {
            try
            {
                var idea = ideasDeNegocio.FirstOrDefault(i => i.Codigo == codigo);
                if (idea == null)
                {
                    return RedirectToAction("Index");
                }

                
                if (idea.Integrantes == null)
                {
                    idea.Integrantes = new List<IntegranteEquipo>();
                }

              
                idea.Integrantes.Add(integrante);

                return RedirectToAction("Detalles", new { codigo });
            }
            catch (Exception ex)
            {
                
                ModelState.AddModelError(string.Empty, "Ocurrió un error al agregar el integrante. Por favor, inténtelo nuevamente.");
                return View();
            }
        }

        public ActionResult IdeasDesarrolloSostenible()
        {
            
            var ideasDesarrolloSostenible = ObtenerIdeasDesarrolloSostenible();

            return View(ideasDesarrolloSostenible);
        }




        [HttpPost]
        public ActionResult EliminarIntegrante(int codigo, string identificacion)
        {
            try
            {
                var idea = ideasDeNegocio.FirstOrDefault(i => i.Codigo == codigo);
                if (idea != null)
                {
                    var integrante = idea.Integrantes.FirstOrDefault(i => i.Identificacion == identificacion);
                    if (integrante != null)
                    {
                        idea.Integrantes.Remove(integrante);
                    }
                }
                return RedirectToAction("Detalles", new { codigo });
            }
            catch (Exception ex)
            {
              
                ModelState.AddModelError(string.Empty, "Ocurrió un error al eliminar el integrante. Por favor, inténtelo nuevamente.");
                return View();
            }
        }


        
        [HttpPost]
        public ActionResult EditarInversionIngresos(int codigo, decimal valorInversion, decimal ingresos3Anios)
        {
            try
            {
                var idea = ideasDeNegocio.FirstOrDefault(i => i.Codigo == codigo);
                if (idea != null)
                {
                    idea.ValorInversion = valorInversion;
                    idea.IngresosGenerados3Anios = ingresos3Anios;
                }
                return RedirectToAction("Detalles", new { codigo });
            }
            catch (Exception ex)
            {
              
                ModelState.AddModelError(string.Empty, "Ocurrió un error al editar los datos. Por favor, inténtelo nuevamente.");
                return View();
            }
        }

    }
}

ProyectoDeAula3/Views/IdeasDeNegocio/AgregarIntegrante.cshtml
@model ProyectoDeAula3.Models.IntegranteEquipo

<h2>Agregar Integrante al Equipo</h2>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.Codigo) 
    <div class="form-group">
        @Html.LabelFor(model => model.Identificacion, "Identificación", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Identificacion, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, "Nombre", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellidos, "Apellidos", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Apellidos, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rol, "Rol", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Rol, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, "Email", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Agregar Integrante" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a Detalles", "Detalles", new { codigo = Model.Codigo }) 
</div>

ProyectoDeAula3/Views/IdeasDeNegocio/Crear.cshtml
@model ProyectoDeAula3.Models.IdeaDeNegocio

<h2>Crear Idea de Negocio</h2>

<form asp-action="Crear" method="post">

    <div class="form-group">
        <label for="Nombre">Nombre de la idea de negocio:</label>
        <input type="text" class="form-control" id="Nombre" name="Nombre">
    </div>
    <div class="form-group">
        <label for="ImpactoSocialOEconomico">Impacto Social o Económico:</label>
        <input type="text" class="form-control" id="ImpactoSocialOEconomico" name="ImpactoSocialOEconomico">
    </div>
    <div class="form-group">
        <label for="ValorInversion">Valor de Inversión:</label>
        <input type="number" class="form-control" id="ValorInversion" name="ValorInversion">
    </div>
    <div class="form-group">
        <label for="IngresosGenerados3Anios">Ingresos Generados en los Primeros 3 Años:</label>
        <input type="number" class="form-control" id="IngresosGenerados3Anios" name="IngresosGenerados3Anios">
    </div>
    <div class="form-group">
        <label for="ValorInversionInfraestructura">Valor de Inversión de Infraestructura, Nube u Onpremise:</label>
        <input type="number" class="form-control" id="ValorInversionInfraestructura" name="ValorInversionInfraestructura">
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DepartamentosBeneficiados, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.DepartamentosBeneficiados,
                new SelectList(ViewBag.Departamentos, "Codigo", "Nombre"),
                new { multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.DepartamentosBeneficiados, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label for="Integrantes">Integrantes del Equipo:</label>
        <table class="table" id="Integrantes">
            <thead>
                <tr>
                    <th>Identificación</th>
                    <th>Nombre</th>
                    <th>Apellidos</th>
                    <th>Rol</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><input type="text" class="form-control" name="Integrantes[0].Identificacion"></td>
                    <td><input type="text" class="form-control" name="Integrantes[0].Nombre"></td>
                    <td><input type="text" class="form-control" name="Integrantes[0].Apellidos"></td>
                    <td><input type="text" class="form-control" name="Integrantes[0].Rol"></td>
                    <td><input type="text" class="form-control" name="Integrantes[0].Email"></td>
                </tr>
                <!-- Agrega más filas para más integrantes según sea necesario -->
            </tbody>
        </table>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Herramientas4RI, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Herramientas4RI,
                (SelectList)ViewBag.Herramientas4RI,
                new { multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.Herramientas4RI, "", new { @class = "text-danger" })
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

ProyectoDeAula3/Views/IdeasDeNegocio/Detalles.cshtml
<a href="@Url.Action("IdeaConMayorImpacto", "IdeasDeNegocio")" class="btn btn-primary">Idea Con Mayor Impacto</a>
<h2></h2>
<a href="@Url.Action("IdeasConImpactoEnMasDe3Departamentos", "IdeasDeNegocio")" class="btn btn-primary">Ideas Con Impacto En Mas De 3 Departamentos</a>
<h2></h2>
<a href="@Url.Action("IdeasMasRentables", "IdeasDeNegocio")" class="btn btn-primary">Ideas Mas Rentables</a>
<h2></h2>
<a href="@Url.Action("IdeasConHerramientas4RI", "IdeasDeNegocio")" class="btn btn-primary">Idea Con Mayor Cantidad De Herramientas 4RI</a>
<h2></h2>
<a href="@Url.Action("IdeasDesarrolloSostenible", "IdeasDeNegocio")" class="btn btn-primary">Ideas con Desarrollo Sostenible</a>
<h2></h2>
<a href="@Url.Action("IdeasConFrasesEspecificas", "IdeasDeNegocio")" class="btn btn-primary">Ideas con "Territorios inteligentes","Transicion energetica"</a>
<h2></h2>
<a href="@Url.Action("IdeaConMayorInversionEnInfraestructura", "IdeasDeNegocio")" class="btn btn-primary">Idea Con Mayor Inversion En Infraestructura</a>

ProyectoDeAula3/Views/IdeasDeNegocio/Editar.cshtml
<a href="@Url.Action("AgregarIntegrante", "IdeasDeNegocio")" class="btn btn-primary">Agregar Integrante</a>
<h2></h2>
<a href="@Url.Action("EliminarIntegrante", "IdeasDeNegocio")" class="btn btn-primary">Eliminar Integrante</a>
<h2></h2>
<a href="@Url.Action("EditarInversionIngresos", "IdeasDeNegocio")" class="btn btn-primary">Editar Inversion Ingresos</a>

ProyectoDeAula3/Views/IdeasDeNegocio/EditarInversionIngresos.cshtml
@model ProyectoDeAula3.Models.IdeaDeNegocio

<h2>Editar Inversión e Ingresos</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.Codigo) 

    <div class="form-group">
        @Html.LabelFor(model => model.ValorInversion, "Nuevo Valor de Inversión", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ValorInversion, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IngresosGenerados3Anios, "Nuevos Ingresos Generados en 3 Años", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.IngresosGenerados3Anios, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Detalles", new { codigo = Model.Codigo }) 
</div>

ProyectoDeAula3/Views/IdeasDeNegocio/EliminarIntegrante.cshtml
@model ProyectoDeAula3.Models.IdeaDeNegocio

<h2>Eliminar Integrante del Equipo</h2>
<p>¿Estás seguro de que deseas eliminar al integrante con Identificación: @ViewBag.Identificacion?</p>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.Codigo) <!-- Campo oculto para el código de la idea de negocio -->
    @Html.Hidden("Identificacion", ViewBag.Identificacion) <!-- Campo oculto para la identificación del integrante -->

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Confirmar Eliminación" class="btn btn-danger" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Detalles", new { codigo = Model.Codigo }) <!-- Enlace para cancelar la eliminación y volver a la vista Detalles -->
</div>

ProyectoDeAula3/Views/IdeasDeNegocio/IdeaConMayorImpacto.cshtml
@model Tuple<ProyectoDeAula3.Models.IdeaDeNegocio, ProyectoDeAula3.Models.IdeaDeNegocio>

<!-- Mostrar información de la idea con mayor impacto -->
<h2>Idea con Mayor Impacto</h2>
@Html.DisplayFor(model => model.Item1)

<!-- Mostrar información de la idea con mayor total de ingresos -->
<h2>Idea con Mayor Total de Ingresos</h2>
@Html.DisplayFor(model => model.Item2)

ProyectoDeAula3/Views/IdeasDeNegocio/IdeaConMayorInversionEnInfraestructura.cshtml
@model ProyectoDeAula3.Models.IdeaDeNegocio

<h2>Idea de Negocio con Mayor Inversión en Infraestructura</h2>
@if (Model != null)
{
    <p>Nombre de la Idea de Negocio: @Model.Nombre</p>
    <p>Inversión en Infraestructura: @Model.ValorInversion</p>
}
else
{
    <p>No hay ideas de negocio con inversión en infraestructura.</p>
}

ProyectoDeAula3/Views/IdeasDeNegocio/IdeasConFrasesEspecificas.cshtml
@model List<ProyectoDeAula3.Models.IdeaDeNegocio>

<h2>Ideas de Negocio con Frases Específicas en su Impacto</h2>
@if (Model.Any())
{
    <ul>
        @foreach (var idea in Model)
        {
            <li>@idea.Nombre</li>
        }
    </ul>
}
else
{
    <p>No hay ideas de negocio con las frases específicas en su impacto.</p>
}

ProyectoDeAula3/Views/IdeasDeNegocio/IdeasConHerramientas4RI.cshtml
@model List<ProyectoDeAula3.Models.IdeaDeNegocio>

<h2>Ideas de Negocio con Herramientas de la 4RI</h2>
@if (Model.Any())
{
    <ul>
        @foreach (var idea in Model)
        {
            <li>@idea.Nombre</li>
        }
    </ul>
}
else
{
    <p>No hay ideas de negocio con herramientas de la 4RI.</p>
}

ProyectoDeAula3/Views/IdeasDeNegocio/IdeasConImpactoEnMasDe3Departamentos.cshtml
@model List<ProyectoDeAula3.Models.IdeaDeNegocio>

<h2>Emprendimientos con Impacto en Más de 3 Departamentos</h2>
<ul>
    @foreach (var idea in Model)
    {
        <li>@idea.Nombre</li>
    }
</ul>

ProyectoDeAula3/Views/IdeasDeNegocio/IdeasDesarrolloSostenible.cshtml
@model List<ProyectoDeAula3.Models.IdeaDeNegocio>

<h2>Ideas de Negocio con Impacto en Desarrollo Sostenible</h2>
<ul>
    @foreach (var idea in Model)
    {
        <li>@idea.Nombre</li>
    }
</ul>

ProyectoDeAula3/Views/IdeasDeNegocio/IdeasMasRentables.cshtml
@model List<ProyectoDeAula3.Models.IdeaDeNegocio>

<h2>Las 3 Ideas Más Rentables</h2>
<ul>
    @foreach (var idea in Model.Take(3))
    {
        <li>@idea.Nombre</li>
    }
</ul>

ProyectoDeAula3/Views/IdeasDeNegocio/Index.cshtml
@model List<ProyectoDeAula3.Models.IdeaDeNegocio>

<h2>Lista de Ideas de Negocio</h2>

<p><a asp-action="Crear">Agregar Nueva Idea de Negocio</a></p>


@if (Model != null && Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nombre</th>
                <th>Impacto Social o Económico</th>
                <th>Valor de Inversión</th>
                <th>Ingresos en 3 Años</th>
                <th>Detalles</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var idea in Model)
            {
                <tr>
                    <td>@idea.Codigo</td>
                    <td>@idea.Nombre</td>
                    <td>@idea.ImpactoSocialOEconomico</td>
                    <td>@idea.ValorInversion</td>
                    <td>@idea.IngresosGenerados3Anios</td>
                    <td><a asp-action="Detalles" asp-route-codigo="@idea.Codigo">Ver Detalles</a></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No hay ideas de negocio disponibles.</p>
}